version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cascade-map-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: cascade_admin
      POSTGRES_PASSWORD: cascade_admin_secret
      POSTGRES_DB: cascade_map
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./scripts/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U cascade_admin -d cascade_map']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
